# Generated by Django 5.2.7 on 2025-11-10 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='Datum (bijv. Maandag 3 november)')),
                ('activities', models.TextField(verbose_name='Activiteiten (bijv. training, lunch, videoanalyse)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Bijzonderheden')),
            ],
            options={
                'verbose_name': 'Dagprogramma',
                'verbose_name_plural': 'Weekprogramma',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam speler')),
                ('injury_type', models.CharField(max_length=100, verbose_name='Blessuretype')),
                ('duration', models.CharField(blank=True, help_text="Bijv. '3 weken', 'tot eind november', etc.", max_length=100, null=True, verbose_name='Duur')),
                ('start_date', models.DateField(blank=True, help_text='Datum waarop blessure begon (optioneel).', null=True, verbose_name='Startdatum')),
            ],
            options={
                'verbose_name': 'Blessure',
                'verbose_name_plural': 'Blessures',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Oefening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100, verbose_name='Speler')),
                ('phase', models.CharField(max_length=100, verbose_name='Fase')),
                ('exercise', models.CharField(blank=True, max_length=150, null=True, verbose_name='Oefening')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschrijving')),
                ('sets_reps', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sets / Herhalingen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum toegevoegd')),
            ],
            options={
                'verbose_name': 'Oefening',
                'verbose_name_plural': 'Oefeningen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prev_weight', models.FloatField(blank=True, null=True, verbose_name='Vorig gewicht (kg)')),
                ('curr_weight', models.FloatField(blank=True, null=True, verbose_name='Huidig gewicht (kg)')),
                ('sum_skinfolds', models.FloatField(blank=True, null=True, verbose_name='Som huidplooien (mm)')),
                ('fat_perc', models.FloatField(blank=True, null=True, verbose_name='Vetpercentage (%)')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam speler')),
                ('sprint_10', models.FloatField(verbose_name='10m Sprint (s)')),
                ('sprint_30', models.FloatField(verbose_name='30m Sprint (s)')),
                ('cmj', models.FloatField(verbose_name='CMJ (cm)')),
                ('squat_jump', models.FloatField(verbose_name='Squat Jump (cm)')),
                ('isrt', models.IntegerField(verbose_name='ISRT (m)')),
            ],
            options={
                'verbose_name': 'Testresultaat',
                'verbose_name_plural': 'Testresultaten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(verbose_name='Weeknummer')),
                ('total_distance', models.FloatField(verbose_name='Totale afstand (m)')),
                ('hsd', models.FloatField(verbose_name='High-speed distance (m)')),
                ('sprints', models.IntegerField(verbose_name='Aantal sprints')),
                ('load', models.FloatField(verbose_name='Trainingsbelasting (arbitraire eenheid)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'Trainingsdata',
                'verbose_name_plural': 'Trainingsdata',
                'ordering': ['player', 'week'],
            },
        ),
    ]
