# Generated by Django 5.2.7 on 2025-11-21 10:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oefening',
            options={'ordering': ['player', '-created_at'], 'verbose_name': 'Oefening', 'verbose_name_plural': 'Oefeningen'},
        ),
        migrations.AlterModelOptions(
            name='playertest',
            options={'ordering': ['name', 'created_at'], 'verbose_name': 'Testresultaat', 'verbose_name_plural': 'Testresultaten'},
        ),
        migrations.AddField(
            model_name='injury',
            name='phase',
            field=models.CharField(choices=[('early', 'Vroege fase'), ('mid', 'Middenfase'), ('final', 'Laatste fase')], default='early', max_length=10, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='oefening',
            name='focus_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/', verbose_name='Profielfoto'),
        ),
        migrations.AddField(
            model_name='player',
            name='nutrition_focus',
            field=models.TextField(blank=True, help_text="Bijv. 'Meer ontbijt eten', 'Extra herstelshake nemen na training', etc.", null=True, verbose_name='Voedingsaandachtspunt'),
        ),
        migrations.AddField(
            model_name='playertest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertest',
            name='curr_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Huidig gewicht (kg)'),
        ),
        migrations.AddField(
            model_name='playertest',
            name='sum_skinfolds',
            field=models.FloatField(blank=True, null=True, verbose_name='Som huidplooien (mm)'),
        ),
        migrations.AlterField(
            model_name='oefening',
            name='player',
            field=models.ForeignKey(blank=True, db_column='player_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
        migrations.CreateModel(
            name='FieldRehabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50, verbose_name='Revalidatiefase')),
                ('onderdeel', models.CharField(max_length=100, verbose_name='Onderdeel')),
                ('afgevinkt', models.BooleanField(default=False, verbose_name='Afgevinkt')),
                ('duur', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duur (min)')),
                ('rpe', models.PositiveIntegerField(blank=True, null=True, verbose_name='RPE (0–10)')),
                ('totale_afstand', models.PositiveIntegerField(blank=True, null=True, verbose_name='Totale afstand (m)')),
                ('afstand_20', models.PositiveIntegerField(blank=True, null=True, verbose_name='>20 km/u (m)')),
                ('afstand_25', models.PositiveIntegerField(blank=True, null=True, verbose_name='>25 km/u (m)')),
                ('acceleraties', models.PositiveIntegerField(blank=True, null=True, verbose_name='Acceleraties')),
                ('deceleraties', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deceleraties')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Veldrevalidatie sessie',
                'verbose_name_plural': 'Veldrevalidatie sessies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopGesprek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('waar_sta_ik_nu', models.TextField(blank=True, null=True, verbose_name='Waar sta ik nu?')),
                ('leerdoelen', models.TextField(blank=True, null=True, verbose_name='Wat zijn mijn leerdoelen?')),
                ('belangrijk', models.TextField(blank=True, null=True, verbose_name='Wat is belangrijk voor mij?')),
                ('komende_periode', models.TextField(blank=True, null=True, verbose_name='Wat ga ik de komende periode doen?')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'POP Gesprek',
                'verbose_name_plural': 'POP Gesprekken',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Programma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Individueel Programma',
                'verbose_name_plural': "Individuele Programma's",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammaOefening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=150)),
                ('duur', models.CharField(blank=True, max_length=50, null=True)),
                ('rpe', models.CharField(blank=True, max_length=20, null=True)),
                ('frequentie', models.CharField(blank=True, max_length=50, null=True)),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('programma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oefeningen', to='main.programma')),
            ],
            options={
                'verbose_name': 'Programma Oefening',
                'verbose_name_plural': 'Programma Oefeningen',
            },
        ),
        migrations.CreateModel(
            name='RPEEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('training_type', models.CharField(max_length=50, verbose_name='Trainingstype')),
                ('rpe', models.IntegerField(verbose_name='RPE (1–10)')),
                ('session_load', models.IntegerField(blank=True, null=True, verbose_name='Sessie Load (optioneel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'RPE Invoer',
                'verbose_name_plural': 'RPE Registraties',
                'ordering': ['-date', 'player'],
            },
        ),
        migrations.CreateModel(
            name='WellnessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('sleep', models.IntegerField(blank=True, null=True, verbose_name='Hoe heb je geslapen? (1–5)')),
                ('mood', models.IntegerField(blank=True, null=True, verbose_name='Hoe voel je je? (1–5)')),
                ('fitness', models.IntegerField(blank=True, null=True, verbose_name='Voel je je fit? (1–5)')),
                ('soreness', models.IntegerField(blank=True, null=True, verbose_name='Spierpijn? (1–5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Opmerkingen')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Wellnessinvoer',
                'verbose_name_plural': 'Wellnessdata',
                'ordering': ['-date', 'player'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('program_text', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'Dagprogramma',
                'verbose_name_plural': "Dagprogramma's",
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
