# Generated by Django 5.2.7 on 2025-11-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_oefening_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep', models.IntegerField(blank=True, null=True, verbose_name='Hoe heb je geslapen?')),
                ('mood', models.IntegerField(blank=True, null=True, verbose_name='Hoe voel je je?')),
                ('fitness', models.IntegerField(blank=True, null=True, verbose_name='Voel je je fit?')),
                ('soreness', models.IntegerField(blank=True, null=True, verbose_name='Spierpijn?')),
                ('rpe', models.IntegerField(blank=True, null=True, verbose_name='RPE (zwaarte training)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Opmerkingen')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'Wellnessinvoer',
                'verbose_name_plural': 'Wellnessdata',
                'ordering': ['-date', 'player'],
            },
        ),
    ]
