# Generated by Django 5.2.7 on 2025-11-21 11:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_oefening_options_alter_playertest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogram',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='dailyprogram',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler'),
        ),
        migrations.AlterField(
            model_name='dailyprogram',
            name='program_text',
            field=models.TextField(blank=True, null=True, verbose_name='Dagprogramma (tekst)'),
        ),
    ]
