# Generated by Django 5.2.7 on 2025-11-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dailyprogram_date_alter_dailyprogram_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('extern', 'Extern (behandeling)'), ('ziek', 'Ziek'), ('training_aangepast', 'Training aangepast'), ('training_uitgevallen', 'Training uitgevallen'), ('training', 'Training'), ('wedstrijd', 'Wedstrijd'), ('training_o21', 'Training O21'), ('wedstrijd_o21', 'Wedstrijd O21'), ('fysio', 'Fysio'), ('overig', 'Overig')], default='training', max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'ordering': ['player'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
