# Generated by Django 5.2.7 on 2025-11-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wellnessentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessentry',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
    ]
