# Generated by Django 5.2.7 on 2025-11-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_wellnessentry_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oefening',
            name='player',
            field=models.ForeignKey(blank=True, db_column='player_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
    ]
