# Generated by Django 5.2.7 on 2025-11-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aanwezigheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('status', models.CharField(choices=[('extern', 'Extern (behandeling)'), ('ziek', 'Ziek'), ('training_aangepast', 'Training aangepast'), ('training_uitgevallen', 'Training uitgevallen'), ('training', 'Training'), ('wedstrijd', 'Wedstrijd'), ('training_o21', 'Training O21'), ('wedstrijd_o21', 'Wedstrijd O21'), ('fysio', 'Fysio'), ('overig', 'Overig')], default='training', max_length=30, verbose_name='Status')),
                ('completed', models.BooleanField(default=False, verbose_name='Ingevuld')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Laatst bijgewerkt')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Aanwezigheid',
                'verbose_name_plural': 'Aanwezigheden',
                'ordering': ['player'],
                'unique_together': {('player', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
