# Generated by Django 5.2.7 on 2025-11-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_oefening_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='phase',
            field=models.CharField(choices=[('early', 'Vroege fase'), ('mid', 'Middenfase'), ('final', 'Laatste fase')], default='early', max_length=10, verbose_name='Fase'),
        ),
    ]
