# Generated by Django 5.2.7 on 2025-11-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aanwezigheid_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.DeleteModel(
            name='PopGesprek',
        ),
    ]
