# Generated by Django 5.2.7 on 2025-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_injury_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nutrition_focus',
            field=models.TextField(blank=True, help_text="Bijv. 'Meer ontbijt eten', 'Extra herstelshake nemen na training', etc.", null=True, verbose_name='Voedingsaandachtspunt'),
        ),
    ]
