# Generated by Django 5.2.7 on 2025-11-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_overig_delete_popgesprek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overig',
            name='player',
        ),
    ]
