# Generated by Django 5.2.7 on 2025-11-11 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_nutrition_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertest',
            name='curr_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Huidig gewicht (kg)'),
        ),
        migrations.AddField(
            model_name='playertest',
            name='sum_skinfolds',
            field=models.FloatField(blank=True, null=True, verbose_name='Som huidplooien (mm)'),
        ),
    ]
