# Generated by Django 5.2.7 on 2025-11-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_playertest_created_at_playertest_curr_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oefening',
            options={'ordering': ['player', '-created_at'], 'verbose_name': 'Oefening', 'verbose_name_plural': 'Oefeningen'},
        ),
        migrations.AlterModelOptions(
            name='playertest',
            options={'ordering': ['name', 'created_at'], 'verbose_name': 'Testresultaat', 'verbose_name_plural': 'Testresultaten'},
        ),
    ]
