# Generated by Django 5.2.7 on 2025-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_oefening_options_alter_playertest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='oefening',
            name='focus_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
