# Generated by Django 5.2.7 on 2025-11-12 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_oefening_focus_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRehabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50, verbose_name='Revalidatiefase')),
                ('onderdeel', models.CharField(max_length=100, verbose_name='Onderdeel')),
                ('afgevinkt', models.BooleanField(default=False, verbose_name='Afgevinkt')),
                ('duur', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duur (min)')),
                ('rpe', models.PositiveIntegerField(blank=True, null=True, verbose_name='RPE (0–10)')),
                ('totale_afstand', models.PositiveIntegerField(blank=True, null=True, verbose_name='Totale afstand (m)')),
                ('afstand_20', models.PositiveIntegerField(blank=True, null=True, verbose_name='>20 km/u (m)')),
                ('afstand_25', models.PositiveIntegerField(blank=True, null=True, verbose_name='>25 km/u (m)')),
                ('acceleraties', models.PositiveIntegerField(blank=True, null=True, verbose_name='Acceleraties')),
                ('deceleraties', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deceleraties')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Veldrevalidatie sessie',
                'verbose_name_plural': 'Veldrevalidatie sessies',
                'ordering': ['-created_at'],
            },
        ),
    ]
