# Generated by Django 5.2.7 on 2025-11-17 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_fieldrehabsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Individueel Programma',
                'verbose_name_plural': "Individuele Programma's",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammaOefening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=150)),
                ('duur', models.CharField(blank=True, max_length=50, null=True)),
                ('rpe', models.CharField(blank=True, max_length=20, null=True)),
                ('frequentie', models.CharField(blank=True, max_length=50, null=True)),
                ('opmerkingen', models.TextField(blank=True, null=True)),
                ('programma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oefeningen', to='main.programma')),
            ],
            options={
                'verbose_name': 'Programma Oefening',
                'verbose_name_plural': 'Programma Oefeningen',
            },
        ),
    ]
