# Generated by Django 5.2.7 on 2025-11-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_programma_programmaoefening'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/', verbose_name='Profielfoto'),
        ),
    ]
