# Generated by Django 5.2.7 on 2025-11-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPEEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('training_type', models.CharField(max_length=50, verbose_name='Trainingstype')),
                ('rpe', models.IntegerField(verbose_name='RPE (1–10)')),
                ('session_load', models.IntegerField(blank=True, null=True, verbose_name='Sessie Load (optioneel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'RPE Invoer',
                'verbose_name_plural': 'RPE Registraties',
                'ordering': ['-date', 'player'],
            },
        ),
    ]
