# Generated by Django 5.2.7 on 2025-11-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rpeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessentry',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='fitness',
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name='Voel je je fit? (1–5)'
            ),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='mood',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hoe voel je je? (1–5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='sleep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hoe heb je geslapen? (1–5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='soreness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Spierpijn? (1–5)'),
        ),
        migrations.CreateModel(
            name='PopGesprek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('doelen_korte_termijn', models.TextField(blank=True, null=True)),
                ('doelen_lange_termijn', models.TextField(blank=True, null=True)),
                ('sterke_punten', models.TextField(blank=True, null=True)),
                ('aandachtspunten', models.TextField(blank=True, null=True)),
                ('coach_opmerkingen', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
    ]
