# Generated by Django 5.2.7 on 2025-11-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rpeentry'),
    ]

    operations = [
    ]
