# Generated by Django 5.2.7 on 2025-11-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_overig_player'),
        ('main', '0016_auto_20251121_0833'),
        ('main', '0016_rename_aandachtspunten_popgesprek_belangrijk_and_more'),
    ]

    operations = [
    ]
