# Generated by Django 5.2.7 on 2025-11-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20251125_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Staflid',
                'verbose_name_plural': 'Stafleden',
                'ordering': ['name'],
            },
        ),
    ]
