# Generated by Django 5.2.7 on 2025-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdata',
            options={'ordering': ['session_date', 'player'], 'verbose_name': 'Trainingsdata', 'verbose_name_plural': 'Trainingsdata'},
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='session_date',
            field=models.DateField(default=None, verbose_name='Datum sessie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='load',
            field=models.FloatField(verbose_name='Trainingsbelasting'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingdata',
            unique_together={('player', 'session_date')},
        ),
    ]
