# Generated by Django 5.2.7 on 2025-11-26 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_trainingdata_options_trainingdata_session_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WedstrijdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='Datum wedstrijd')),
                ('week', models.PositiveIntegerField(verbose_name='Weeknummer')),
                ('total_distance', models.FloatField(verbose_name='Totale afstand (m)')),
                ('hsd', models.FloatField(verbose_name='High-speed distance (m)')),
                ('sprints', models.IntegerField(verbose_name='Aantal sprints')),
                ('load', models.FloatField(verbose_name='Wedstrijdbelasting')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'verbose_name': 'Wedstrijddata',
                'verbose_name_plural': 'Wedstrijddata',
                'ordering': ['match_date', 'player'],
                'unique_together': {('player', 'match_date')},
            },
        ),
    ]
