# Generated by Django 5.2.7 on 2025-11-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_wedstrijddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Spits', 'Spits'), ('Targetman', 'Targetman'), ('Buitenspeler', 'Buitenspeler'), ('Dynamische middenvelder', 'Dynamische middenvelder'), ('Controlerende middenvelder', 'Controlerende middenvelder'), ('Centrale verdediger', 'Centrale verdediger'), ('Vleugelverdediger', 'Vleugelverdediger')], max_length=50, null=True, verbose_name='Positie'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naam speler'),
        ),
    ]
