# Generated by Django 5.2.7 on 2025-11-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_player_position_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedstrijddata',
            name='accelerations',
            field=models.IntegerField(default=0, verbose_name='Accelerations (Absolute)'),
        ),
        migrations.AddField(
            model_name='wedstrijddata',
            name='decelerations',
            field=models.IntegerField(default=0, verbose_name='Decelerations (Absolute)'),
        ),
        migrations.AddField(
            model_name='wedstrijddata',
            name='his',
            field=models.FloatField(default=0, verbose_name='HIS (m >25 km/u)'),
        ),
        migrations.AlterField(
            model_name='wedstrijddata',
            name='hsd',
            field=models.FloatField(default=0, verbose_name='HIR (m >20 km/u)'),
        ),
        migrations.AlterField(
            model_name='wedstrijddata',
            name='load',
            field=models.FloatField(default=0, verbose_name='HML Distance (m)'),
        ),
        migrations.AlterField(
            model_name='wedstrijddata',
            name='sprints',
            field=models.IntegerField(default=0, verbose_name='Aantal sprints'),
        ),
        migrations.AlterField(
            model_name='wedstrijddata',
            name='total_distance',
            field=models.FloatField(default=0, verbose_name='Totale afstand (m)'),
        ),
    ]
