# Generated by Django 5.2.7 on 2025-12-05 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_wedstrijddata_accelerations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HitWeekPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monday', models.CharField(blank=True, max_length=255)),
                ('tuesday', models.CharField(blank=True, max_length=255)),
                ('wednesday', models.CharField(blank=True, max_length=255)),
                ('thursday', models.CharField(blank=True, max_length=255)),
                ('friday', models.CharField(blank=True, max_length=255)),
                ('saturday', models.CharField(blank=True, max_length=255)),
                ('sunday', models.CharField(blank=True, max_length=255)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
