# Generated by Django 5.2.7 on 2025-12-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_hitweekplanning_trainer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertest',
            options={'ordering': ['player', '-created_at'], 'verbose_name': 'Testresultaat', 'verbose_name_plural': 'Testresultaten'},
        ),
        migrations.RemoveField(
            model_name='playertest',
            name='name',
        ),
        migrations.AddField(
            model_name='playertest',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='main.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertest',
            name='submax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='cmj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='curr_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='isrt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='sprint_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='sprint_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='squat_jump',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='sum_skinfolds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
