# Generated by Django 5.2.7 on 2025-12-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_playertest_options_remove_playertest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertest',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Lengte (cm)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='cmj',
            field=models.FloatField(blank=True, null=True, verbose_name='CMJ (cm)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='curr_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Gewicht (kg)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='isrt',
            field=models.FloatField(blank=True, null=True, verbose_name='ISRT (m)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='sprint_10',
            field=models.FloatField(blank=True, null=True, verbose_name='10m sprint (s)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='sprint_30',
            field=models.FloatField(blank=True, null=True, verbose_name='30m sprint (s)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='squat_jump',
            field=models.FloatField(blank=True, null=True, verbose_name='Squat Jump (cm)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='submax',
            field=models.FloatField(blank=True, null=True, verbose_name='Submaximaal (%HRmax)'),
        ),
        migrations.AlterField(
            model_name='playertest',
            name='sum_skinfolds',
            field=models.FloatField(blank=True, null=True, verbose_name='Som huidplooien (mm)'),
        ),
    ]
