# Generated by Django 5.2.7 on 2025-12-10 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_playertest_length_alter_playertest_cmj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertest',
            options={'ordering': ['-test_date'], 'verbose_name': 'Testresultaat', 'verbose_name_plural': 'Testresultaten'},
        ),
        migrations.AddField(
            model_name='playertest',
            name='test_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum meting'),
        ),
    ]
