# Generated by Django 5.2.7 on 2025-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_playertest_options_playertest_test_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Maandag', 'Maandag'), ('Dinsdag', 'Dinsdag'), ('Woensdag', 'Woensdag'), ('Donderdag', 'Donderdag'), ('Vrijdag', 'Vrijdag'), ('Zaterdag', 'Zaterdag'), ('Zondag', 'Zondag')], max_length=20, unique=True)),
                ('meal', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('red', 'Rood'), ('yellow', 'Geel'), ('green', 'Groen')], max_length=20)),
            ],
        ),
    ]
