# Generated by Django 5.2.7 on 2025-12-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_nutritionday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antropometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body_mass', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('triceps_m1', models.FloatField(blank=True, null=True)),
                ('triceps_m2', models.FloatField(blank=True, null=True)),
                ('triceps_m3', models.FloatField(blank=True, null=True)),
                ('biceps_m1', models.FloatField(blank=True, null=True)),
                ('biceps_m2', models.FloatField(blank=True, null=True)),
                ('biceps_m3', models.FloatField(blank=True, null=True)),
                ('subscapular_m1', models.FloatField(blank=True, null=True)),
                ('subscapular_m2', models.FloatField(blank=True, null=True)),
                ('subscapular_m3', models.FloatField(blank=True, null=True)),
                ('iliac_crest_m1', models.FloatField(blank=True, null=True)),
                ('iliac_crest_m2', models.FloatField(blank=True, null=True)),
                ('iliac_crest_m3', models.FloatField(blank=True, null=True)),
                ('supraspinale_m1', models.FloatField(blank=True, null=True)),
                ('supraspinale_m2', models.FloatField(blank=True, null=True)),
                ('supraspinale_m3', models.FloatField(blank=True, null=True)),
                ('abdominal_m1', models.FloatField(blank=True, null=True)),
                ('abdominal_m2', models.FloatField(blank=True, null=True)),
                ('abdominal_m3', models.FloatField(blank=True, null=True)),
                ('thigh_m1', models.FloatField(blank=True, null=True)),
                ('thigh_m2', models.FloatField(blank=True, null=True)),
                ('thigh_m3', models.FloatField(blank=True, null=True)),
                ('calf_m1', models.FloatField(blank=True, null=True)),
                ('calf_m2', models.FloatField(blank=True, null=True)),
                ('calf_m3', models.FloatField(blank=True, null=True)),
                ('arm_relaxed_m1', models.FloatField(blank=True, null=True)),
                ('arm_relaxed_m2', models.FloatField(blank=True, null=True)),
                ('arm_relaxed_m3', models.FloatField(blank=True, null=True)),
                ('arm_flexed_m1', models.FloatField(blank=True, null=True)),
                ('arm_flexed_m2', models.FloatField(blank=True, null=True)),
                ('arm_flexed_m3', models.FloatField(blank=True, null=True)),
                ('thigh_girth_m1', models.FloatField(blank=True, null=True)),
                ('thigh_girth_m2', models.FloatField(blank=True, null=True)),
                ('thigh_girth_m3', models.FloatField(blank=True, null=True)),
                ('calf_girth_m1', models.FloatField(blank=True, null=True)),
                ('calf_girth_m2', models.FloatField(blank=True, null=True)),
                ('calf_girth_m3', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antropometry', to='main.player')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
