# Generated by Django 5.2.7 on 2025-12-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_antropometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropometry',
            name='fat_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antropometry',
            name='fat_carter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antropometry',
            name='fat_dw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antropometry',
            name='fat_faulkner',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
