# Generated by Django 5.2.7 on 2026-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_antropometry_fat_average_antropometry_fat_carter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['kickoff'],
                'constraints': [models.UniqueConstraint(fields=('kickoff', 'home', 'away'), name='unique_match')],
            },
        ),
    ]
