# Generated by Django 5.2.7 on 2026-02-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionday',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Rood'), ('yellow', 'Geel'), ('green', 'Groen')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='meal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PlayerIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
                ('breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('snack1', models.CharField(blank=True, max_length=255, null=True)),
                ('lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('snack2', models.CharField(blank=True, max_length=255, null=True)),
                ('dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('snack3', models.CharField(blank=True, max_length=255, null=True)),
                ('next_meeting_goal', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='main.player')),
            ],
        ),
    ]
