# Generated by Django 5.2.7 on 2026-02-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_nutritionday_color_alter_nutritionday_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('role', models.CharField(blank=True, choices=[('Speler', 'Speler'), ('Staf', 'Staf'), ('Overig', 'Overig')], max_length=20, null=True, verbose_name='Rol')),
                ('date', models.DateField(verbose_name='Geboortedatum')),
            ],
            options={
                'verbose_name': 'Verjaardag',
                'verbose_name_plural': 'Verjaardagen',
                'ordering': ['date', 'name'],
            },
        ),
    ]
