# Generated by Django 5.2.7 on 2026-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('team', models.CharField(blank=True, max_length=100, null=True, verbose_name='Team')),
                ('week_of', models.DateField(blank=True, null=True, verbose_name='Week van')),
            ],
            options={
                'verbose_name': 'Meetrainer jeugd',
                'verbose_name_plural': 'Meetrainers jeugd',
                'ordering': ['-week_of', 'name'],
            },
        ),
        migrations.AddField(
            model_name='playerintake',
            name='supplements',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
