# Generated by Django 5.2.7 on 2026-02-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_youthguest_playerintake_supplements'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthguest',
            name='days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dagen'),
        ),
    ]
