# Generated by Django 5.2.7 on 2026-02-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_youthguest_days_weightentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='VakantieProgrammaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('loopvorm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loopvorm')),
                ('kracht', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kracht')),
                ('completed', models.BooleanField(default=False, verbose_name='Uitgevoerd')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Vakantieprogramma item',
                'verbose_name_plural': 'Vakantieprogramma items',
                'ordering': ['-date', 'player'],
            },
        ),
    ]
