# Generated by Django 5.2.7 on 2026-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_vakantieprogrammaentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='VakantiePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('loopvorm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loopvorm')),
                ('kracht', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kracht')),
                ('visible_from', models.DateField(verbose_name='Zichtbaar vanaf')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Zichtbaar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(related_name='vakantie_planningen', to='main.player', verbose_name='Spelers')),
            ],
            options={
                'verbose_name': 'Vakantieplanning',
                'verbose_name_plural': 'Vakantieplanningen',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
