# Generated by Django 5.2.7 on 2026-02-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_3nf_phase1_foundation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='injurycase',
            new_name='main_injury_player__4e7bb7_idx',
            old_name='main_injuryc_player__8c0f5b_idx',
        ),
        migrations.RenameIndex(
            model_name='injurycase',
            new_name='main_injury_started_738f54_idx',
            old_name='main_injuryc_started_34f452_idx',
        ),
    ]
