# Generated by Django 5.2.7 on 2026-02-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_backfill_anthropometry_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anthropometrymeasurement',
            new_name='main_anthro_categor_c3426b_idx',
            old_name='main_anthro_category_3366cb_idx',
        ),
    ]
