# Generated by Django 5.2.7 on 2026-02-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_match_team_3nf'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='main_attend_date_35e05c_idx',
            old_name='main_attend_date_1efd36_idx',
        ),
        migrations.RenameIndex(
            model_name='nutritionintakesession',
            new_name='main_nutrit_player__b27b72_idx',
            old_name='main_nutrit_player__b53571_idx',
        ),
        migrations.RenameIndex(
            model_name='overignote',
            new_name='main_overig_note_ty_12667b_idx',
            old_name='main_overign_note_ty_5f60f5_idx',
        ),
        migrations.RenameIndex(
            model_name='overignote',
            new_name='main_overig_created_a44713_idx',
            old_name='main_overign_created_32941d_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='main_perfor_metric__11adaa_idx',
            old_name='main_perfor_metric__55685d_idx',
        ),
        migrations.RenameIndex(
            model_name='performancesession',
            new_name='main_perfor_session_becece_idx',
            old_name='main_perfor_session_8134f5_idx',
        ),
        migrations.RenameIndex(
            model_name='performancesession',
            new_name='main_perfor_player__4b4079_idx',
            old_name='main_perfor_player__1b5325_idx',
        ),
        migrations.AlterField(
            model_name='fieldrehabsession',
            name='rpe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RPE (0â€“10)'),
        ),
        migrations.AlterField(
            model_name='rpeentry',
            name='rpe',
            field=models.IntegerField(verbose_name='RPE (1â€“10)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='fitness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Voel je je fit? (1â€“5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='mood',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hoe voel je je? (1â€“5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='sleep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hoe heb je geslapen? (1â€“5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='soreness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Spierpijn? (1â€“5)'),
        ),
        migrations.AddIndex(
            model_name='rpeentry',
            index=models.Index(fields=['date', 'player'], name='main_rpeent_date_fbec02_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnessentry',
            index=models.Index(fields=['date', 'player'], name='main_wellne_date_cc439a_idx'),
        ),
        migrations.AddConstraint(
            model_name='rpeentry',
            constraint=models.UniqueConstraint(fields=('player', 'date'), name='uniq_rpe_player_date'),
        ),
        migrations.AddConstraint(
            model_name='wellnessentry',
            constraint=models.UniqueConstraint(fields=('player', 'date'), name='uniq_wellness_player_date'),
        ),
    ]
