# Generated by Django 5.2.4 on 2026-03-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_youthguest_team_lookup_3nf'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='injurycase',
            name='main_injury_player__4e7bb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='programmaoefening',
            name='main_progra_frequen_5b27e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='programmaoefening',
            name='main_progra_duur_un_9db8f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='programmaoefening',
            name='main_progra_duur_va_237147_idx',
        ),
        migrations.RemoveIndex(
            model_name='programmaoefening',
            name='main_progra_naam_re_44f130_idx',
        ),
        migrations.RemoveIndex(
            model_name='rpeentry',
            name='main_rpeent_trainin_a0f54b_idx',
        ),
        migrations.RemoveIndex(
            model_name='youthguestprofile',
            name='main_youthg_team_re_8fceab_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldrehabmetric',
            new_name='main_fieldr_session_143f39_idx',
            old_name='main_fieldr_session_10d2d1_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldrehabmetric',
            new_name='main_fieldr_metric__0a182e_idx',
            old_name='main_fieldr_metric_t_4b5748_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldrehabsession',
            new_name='main_fieldr_player__292ad7_idx',
            old_name='main_fieldr_player__f9d60d_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldrehabsession',
            new_name='main_fieldr_phase_r_edbaf4_idx',
            old_name='main_fieldr_phase_r_9f7c42_idx',
        ),
        migrations.RenameIndex(
            model_name='hitasrplanentry',
            new_name='main_hitasr_session_33b779_idx',
            old_name='main_hitasr_session_e57696_idx',
        ),
        migrations.RenameIndex(
            model_name='hitasrplanentry',
            new_name='main_hitasr_player__061754_idx',
            old_name='main_hitasr_player__384ed0_idx',
        ),
        migrations.RenameIndex(
            model_name='hitasrplansession',
            new_name='main_hitasr_session_3026b4_idx',
            old_name='main_hitasr_session_494a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='hitasrplansession',
            new_name='main_hitasr_created_9656eb_idx',
            old_name='main_hitasr_created_f77e65_idx',
        ),
        migrations.RenameIndex(
            model_name='injurycase',
            new_name='main_injury_player__503bda_idx',
            old_name='main_injuryc_player__3nf_idx',
        ),
        migrations.RenameIndex(
            model_name='oefening',
            new_name='main_oefeni_program_6fa76b_idx',
            old_name='main_oefeni_program_9e8be1_idx',
        ),
        migrations.RenameIndex(
            model_name='playerspeedtest',
            new_name='main_player_player__54dc7a_idx',
            old_name='main_players_player__2f9317_idx',
        ),
        migrations.RenameIndex(
            model_name='playerspeedtest',
            new_name='main_player_test_da_19ee67_idx',
            old_name='main_players_test_da_2efea4_idx',
        ),
        migrations.AlterField(
            model_name='rpeentry',
            name='rpe',
            field=models.IntegerField(verbose_name='RPE (1ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“10)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='fitness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Voel je je fit? (1ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='mood',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hoe voel je je? (1ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='sleep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hoe heb je geslapen? (1ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“5)'),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='soreness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Spierpijn? (1ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“5)'),
        ),
    ]
