# Generated by Django 5.2.4 on 2026-03-03 12:01

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    PerformanceSession = apps.get_model('main', 'PerformanceSession')
    PerformanceSessionKind = apps.get_model('main', 'PerformanceSessionKind')
    label_map = {
        'training': 'Training',
        'match': 'Wedstrijd',
        'test': 'Test',
    }
    cache = {}
    for row in PerformanceSession.objects.all().iterator():
        code = (getattr(row, 'session_kind', None) or '').strip().lower()
        if not code:
            continue
        if code not in cache:
            cache[code], _ = PerformanceSessionKind.objects.get_or_create(
                code=code,
                defaults={'label': label_map.get(code, code.replace('_', ' ').title())},
            )
        row.session_kind_ref_id = cache[code].id
        row.save(update_fields=['session_kind_ref'])


def backwards(apps, schema_editor):
    PerformanceSession = apps.get_model('main', 'PerformanceSession')
    for row in PerformanceSession.objects.select_related('session_kind_ref').all().iterator():
        row.session_kind = row.session_kind_ref.code if row.session_kind_ref_id else None
        row.save(update_fields=['session_kind'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_remove_injurycase_main_injury_player__4e7bb7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSessionKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AlterModelOptions(
            name='performancesession',
            options={'ordering': ['-session_date', 'player__name', 'session_kind_ref__code']},
        ),
        migrations.RemoveConstraint(
            model_name='performancesession',
            name='uniq_perf_session_per_source',
        ),
        migrations.RemoveIndex(
            model_name='performancesession',
            name='main_perfor_session_becece_idx',
        ),
        migrations.AddField(
            model_name='performancesession',
            name='session_kind_ref',
            field=models.ForeignKey(blank=True, db_column='session_kind_ref_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='main.performancesessionkind'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='performancesession',
            name='session_kind_ref',
            field=models.ForeignKey(db_column='session_kind_ref_id', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='main.performancesessionkind'),
        ),
        migrations.RemoveField(
            model_name='performancesession',
            name='session_kind',
        ),
        migrations.AddIndex(
            model_name='performancesession',
            index=models.Index(fields=['session_kind_ref', 'session_date'], name='main_perfor_session_f2abd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancesession',
            constraint=models.UniqueConstraint(fields=('player', 'session_kind_ref', 'session_date', 'source_legacy_table', 'source_legacy_id'), name='uniq_perf_session_per_source'),
        ),
    ]
