# Generated by Django 5.2.4 on 2026-03-03 13:56

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    IndividualDayPlanNote = apps.get_model('main', 'IndividualDayPlanNote')
    IndividualDayPlanNoteType = apps.get_model('main', 'IndividualDayPlanNoteType')
    label_map = {
        'program_text': 'Programma tekst',
    }
    cache = {}
    for row in IndividualDayPlanNote.objects.all().iterator():
        code = (getattr(row, 'note_type', None) or '').strip().lower()
        if not code:
            continue
        if code not in cache:
            cache[code], _ = IndividualDayPlanNoteType.objects.get_or_create(
                code=code,
                defaults={'label': label_map.get(code, code.replace('_', ' ').title())},
            )
        row.note_type_ref_id = cache[code].id
        row.save(update_fields=['note_type_ref'])


def backwards(apps, schema_editor):
    IndividualDayPlanNote = apps.get_model('main', 'IndividualDayPlanNote')
    for row in IndividualDayPlanNote.objects.select_related('note_type_ref').all().iterator():
        row.note_type = row.note_type_ref.code if row.note_type_ref_id else None
        row.save(update_fields=['note_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_performancesessionkind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDayPlanNoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AlterModelOptions(
            name='individualdayplannote',
            options={'ordering': ['note_type_ref__code', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='individualdayplannote',
            name='uniq_individual_day_plan_note_type',
        ),
        migrations.AddField(
            model_name='individualdayplannote',
            name='note_type_ref',
            field=models.ForeignKey(blank=True, db_column='note_type_ref_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='main.individualdayplannotetype'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='individualdayplannote',
            name='note_type_ref',
            field=models.ForeignKey(db_column='note_type_ref_id', on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='main.individualdayplannotetype'),
        ),
        migrations.RemoveField(
            model_name='individualdayplannote',
            name='note_type',
        ),
        migrations.AddConstraint(
            model_name='individualdayplannote',
            constraint=models.UniqueConstraint(fields=('plan', 'note_type_ref'), name='uniq_individual_day_plan_note_type'),
        ),
    ]
