# Generated by Django 5.2.4 on 2026-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_individualdayplannotetype_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nutritionintakesession',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', False)), fields=('player', 'date'), name='uniq_nutri_session_player_date'),
        ),
        migrations.AddConstraint(
            model_name='playerspeedtest',
            constraint=models.CheckConstraint(condition=models.Q(('mss_kmh__gt', 0)), name='ck_speedtest_mss_pos'),
        ),
        migrations.AddConstraint(
            model_name='playerspeedtest',
            constraint=models.CheckConstraint(condition=models.Q(('mas_kmh__gt', 0)), name='ck_speedtest_mas_pos'),
        ),
        migrations.AddConstraint(
            model_name='rpeentry',
            constraint=models.CheckConstraint(condition=models.Q(('rpe__gte', 1), ('rpe__lte', 10)), name='ck_rpe_between_1_10'),
        ),
        migrations.AddConstraint(
            model_name='rpeentry',
            constraint=models.CheckConstraint(condition=models.Q(('session_load__isnull', True), ('session_load__gte', 0), _connector='OR'), name='ck_rpe_session_load_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='weightentry',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='ck_weight_pos'),
        ),
        migrations.AddConstraint(
            model_name='wellnessentry',
            constraint=models.CheckConstraint(condition=models.Q(('sleep__isnull', True), models.Q(('sleep__gte', 1), ('sleep__lte', 5)), _connector='OR'), name='ck_well_sleep_1_5'),
        ),
        migrations.AddConstraint(
            model_name='wellnessentry',
            constraint=models.CheckConstraint(condition=models.Q(('mood__isnull', True), models.Q(('mood__gte', 1), ('mood__lte', 5)), _connector='OR'), name='ck_well_mood_1_5'),
        ),
        migrations.AddConstraint(
            model_name='wellnessentry',
            constraint=models.CheckConstraint(condition=models.Q(('fitness__isnull', True), models.Q(('fitness__gte', 1), ('fitness__lte', 5)), _connector='OR'), name='ck_well_fit_1_5'),
        ),
        migrations.AddConstraint(
            model_name='wellnessentry',
            constraint=models.CheckConstraint(condition=models.Q(('soreness__isnull', True), models.Q(('soreness__gte', 1), ('soreness__lte', 5)), _connector='OR'), name='ck_well_sore_1_5'),
        ),
    ]
