# Generated by Django 5.2.4 on 2026-03-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_nutritionintakesession_uniq_nutri_session_player_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nutritionintakesession',
            name='uniq_nutri_session_player_date',
        ),
        migrations.AddConstraint(
            model_name='nutritionintakesession',
            constraint=models.UniqueConstraint(fields=('player', 'date'), name='uniq_nutri_session_player_date'),
        ),
    ]
