# Generated by Django 5.2.4 on 2026-03-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_remove_nutritionintakesession_uniq_nutri_session_player_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeweeganalyseOnderdeel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BeweeganalysePunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('focus_text', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onderdeel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punten', to='main.beweeganalyseonderdeel')),
            ],
            options={
                'ordering': ['onderdeel__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BeweeganalyseSessie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beweeganalyse_sessies', to='main.player')),
            ],
            options={
                'ordering': ['-date', 'player__name'],
            },
        ),
        migrations.CreateModel(
            name='BeweeganalyseBeoordeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('punt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beoordelingen', to='main.beweeganalysepunt')),
                ('sessie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beoordelingen', to='main.beweeganalysesessie')),
            ],
            options={
                'ordering': ['punt__onderdeel__sort_order', 'punt__sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='beweeganalysepunt',
            constraint=models.UniqueConstraint(fields=('onderdeel', 'title', 'sort_order'), name='uniq_beweeganalyse_punt_template'),
        ),
        migrations.AddConstraint(
            model_name='beweeganalysesessie',
            constraint=models.UniqueConstraint(fields=('player', 'date'), name='uniq_beweeganalyse_sessie_player_date'),
        ),
        migrations.AddConstraint(
            model_name='beweeganalysebeoordeling',
            constraint=models.UniqueConstraint(fields=('sessie', 'punt'), name='uniq_beweeganalyse_sessie_punt'),
        ),
        migrations.AddConstraint(
            model_name='beweeganalysebeoordeling',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 1), ('score__lte', 4)), _connector='OR'), name='ck_beweeganalyse_score_1_4'),
        ),
    ]
