# Generated by Codex on 2026-03-06
from django.db import migrations


def seed_beweeganalyse_template(apps, schema_editor):
    Onderdeel = apps.get_model("main", "BeweeganalyseOnderdeel")
    Punt = apps.get_model("main", "BeweeganalysePunt")

    template = [
        (
            "Sprint – Acceleratie (0–10m)",
            10,
            [
                ("Posture", "Diagonale Lijn, Rechte Rug", 10),
                ("Hiplock", "Knee Drive", 20),
                ("Footplant", "Ankle Stiffness", 30),
            ],
        ),
        (
            "Sprint – Top Speed (20–30m)",
            20,
            [
                ("Posture", "12:05 Height, Core Control", 10),
                ("Hiplock", "Knee Drive", 20),
                ("Footplant", "Ankle Stiffness, Voetpositie Neutraal", 30),
            ],
        ),
        (
            "COD – 180° -> 180° (Links)",
            30,
            [
                ("Posture", "Diagonale Lijn, Low Stance, Trunk Position", 10),
                ("Hiplock", "Vervolg Stap, Volledige Draai (Geen Overstap)", 20),
                ("Footplant", "Ankle Stiffness, Voetpositie Neutraal", 30),
            ],
        ),
        (
            "COD – 180° -> 180° (Rechts)",
            40,
            [
                ("Posture", "Diagonale Lijn, Low Stance, Trunk Position", 10),
                ("Hiplock", "Vervolg Stap, Volledige Draai (Geen Overstap)", 20),
                ("Footplant", "Ankle Stiffness, Voetpositie Neutraal", 30),
            ],
        ),
    ]

    for onderdeel_name, onderdeel_order, points in template:
        onderdeel, _ = Onderdeel.objects.get_or_create(
            name=onderdeel_name,
            defaults={"sort_order": onderdeel_order, "is_active": True},
        )
        if onderdeel.sort_order != onderdeel_order:
            onderdeel.sort_order = onderdeel_order
            onderdeel.save(update_fields=["sort_order"])

        for title, focus_text, point_order in points:
            Punt.objects.get_or_create(
                onderdeel=onderdeel,
                title=title,
                sort_order=point_order,
                defaults={
                    "focus_text": focus_text,
                    "is_active": True,
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0079_beweeganalyseonderdeel_beweeganalysepunt_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_beweeganalyse_template, noop_reverse),
    ]

