# Generated by Django 5.2.4 on 2026-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_seed_beweeganalyse_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='beweeganalysesessie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='beweeganalyse_videos/'),
        ),
    ]
