# Generated by Codex on 2026-03-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0081_beweeganalysesessie_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="beweeganalysebeoordeling",
            name="priority_flag",
            field=models.BooleanField(default=False),
        ),
    ]

