# Generated by Codex on 2026-03-06
from django.db import migrations


def seed_medisch_section(apps, schema_editor):
    Onderdeel = apps.get_model("main", "BeweeganalyseOnderdeel")
    Punt = apps.get_model("main", "BeweeganalysePunt")

    medisch, _ = Onderdeel.objects.get_or_create(
        name="Medisch",
        defaults={"sort_order": 50, "is_active": True},
    )
    if medisch.sort_order != 50:
        medisch.sort_order = 50
        medisch.save(update_fields=["sort_order"])

    Punt.objects.get_or_create(
        onderdeel=medisch,
        title="Zittende loopstijl",
        sort_order=10,
        defaults={
            "focus_text": "Lopen op de hakken, been voor zich leidt tot een overmatig gebruik van de quadriceps.",
            "is_active": True,
        },
    )
    Punt.objects.get_or_create(
        onderdeel=medisch,
        title="Knie lijn (180 graden)",
        sort_order=20,
        defaults={
            "focus_text": "Gasbeen strikt in de looprichting houden; knie in lijn houden zonder afwijking naar binnen of buiten.",
            "is_active": True,
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0082_beweeganalysebeoordeling_priority_flag"),
    ]

    operations = [
        migrations.RunPython(seed_medisch_section, noop_reverse),
    ]

