# Generated by Django 5.2.4 on 2026-03-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_seed_beweeganalyse_medisch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeweeganalyseOefening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('punt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oefeningen', to='main.beweeganalysepunt')),
            ],
            options={
                'ordering': ['punt__onderdeel__sort_order', 'punt__sort_order', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('punt', 'name'), name='uniq_beweeganalyse_oefening_punt_name')],
            },
        ),
    ]
