# Generated by Codex on 2026-03-06
from django.db import migrations


def seed_beweeganalyse_oefeningen(apps, schema_editor):
    Punt = apps.get_model("main", "BeweeganalysePunt")
    Oefening = apps.get_model("main", "BeweeganalyseOefening")

    mapping = [
        (
            "Sprint",
            "Acceleratie",
            "Posture",
            [
                "TRX fall out",
                "Resisted sprints",
            ],
        ),
        (
            "Sprint",
            "Acceleratie",
            "Hiplock",
            [
                "Weighted hip flexor lift",
                "0 deg hops",
            ],
        ),
        (
            "Sprint",
            "Acceleratie",
            "Footplant",
            [
                "Drop/depth jumps",
                "Split stance jumps (90 graden) / switch jumps",
            ],
        ),
        (
            "Sprint",
            "Top Speed",
            "Posture",
            [
                "Pogo switch jump",
                "Awkward farmer carries (met gewicht, arm boven/onder) + A-marches",
                "Hamstring switches (vanuit glute bridge) / SL hamstring eccentrisch falls",
                "Loopwerk/loopscholing met stok boven het hoofd",
            ],
        ),
        (
            "Sprint",
            "Top Speed",
            "Hiplock",
            [
                "Bounding",
                "Wall drills (verticaal)",
            ],
        ),
        (
            "Sprint",
            "Top Speed",
            "Footplant",
            [
                "Pogo's (double leg/single leg, split stance)",
                "Bounding (horizontal) op snelheid",
            ],
        ),
        (
            "COD",
            "Links",
            "Posture",
            [
                "Max effort 90 degree hop",
                "Depth jump (zijwaarts landen)",
                "Broad jump max effort zero degree turn",
            ],
        ),
        (
            "COD",
            "Rechts",
            "Posture",
            [
                "Max effort 90 degree hop",
                "Depth jump (zijwaarts landen)",
                "Broad jump max effort zero degree turn",
            ],
        ),
        (
            "COD",
            "Links",
            "Hiplock",
            [
                "Skater jumps (variant kiezen)",
                "Inner decel (depth jump) / running direction change",
                "Broad jump max effort zero degree turn",
                "Extra (rotatie): oblique oefeningen, alleen inzetten als speler er klaar voor is",
            ],
        ),
        (
            "COD",
            "Rechts",
            "Hiplock",
            [
                "Skater jumps (variant kiezen)",
                "Inner decel (depth jump) / running direction change",
                "Broad jump max effort zero degree turn",
                "Extra (rotatie): oblique oefeningen, alleen inzetten als speler er klaar voor is",
            ],
        ),
    ]

    for contains_a, contains_b, point_title, oefeningen in mapping:
        punt = (
            Punt.objects.filter(
                onderdeel__name__icontains=contains_a,
                title=point_title,
            )
            .filter(onderdeel__name__icontains=contains_b)
            .order_by("id")
            .first()
        )
        if not punt:
            continue

        for idx, naam in enumerate(oefeningen, start=1):
            Oefening.objects.get_or_create(
                punt=punt,
                name=naam,
                defaults={"sort_order": idx * 10, "is_active": True},
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0084_beweeganalyseoefening"),
    ]

    operations = [
        migrations.RunPython(seed_beweeganalyse_oefeningen, noop_reverse),
    ]
