# Generated by Django 6.0.5 on 2026-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actief'),
        ),
    ]
