# Generated by Django 6.0.5 on 2026-06-12 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_player_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dayprogramentry',
            index=models.Index(fields=['team', 'date'], name='main_day_team_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dayprogramentry',
            index=models.Index(fields=['team', 'category', 'date'], name='main_day_team_cat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dayprogramentry',
            index=models.Index(fields=['date', 'category'], name='main_day_date_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='performancesession',
            index=models.Index(fields=['player', 'session_kind_ref', 'session_date'], name='main_perf_player_kind_date_idx'),
        ),
        migrations.AddIndex(
            model_name='performancesession',
            index=models.Index(fields=['source_legacy_table', 'source_legacy_id'], name='main_perf_source_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_active', 'name'], name='main_player_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position_ref', 'is_active'], name='main_player_pos_active_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamassignment',
            index=models.Index(fields=['team', 'end_date', 'start_date'], name='main_assign_team_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamassignment',
            index=models.Index(fields=['player', 'end_date', 'start_date'], name='main_assign_player_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamassignment',
            index=models.Index(fields=['team', 'player'], name='main_assign_team_player_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingweektarget',
            index=models.Index(fields=['updated_at'], name='main_weektarget_updated_idx'),
        ),
    ]
