# Generated by Django 6.0.5 on 2026-06-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_dayprogramentry_main_day_team_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=60)),
                ('object_label', models.CharField(blank=True, default='', max_length=160)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activiteitenlog',
                'verbose_name_plural': 'Activiteitenlogs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='main_audit_actor_date_idx'), models.Index(fields=['category', 'created_at'], name='main_audit_cat_date_idx'), models.Index(fields=['action', 'created_at'], name='main_audit_action_date_idx')],
            },
        ),
    ]
