# Generated by Django 6.0.5 on 2026-06-12 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=40)),
                ('team_code', models.CharField(blank=True, default='', max_length=30)),
                ('team_label', models.CharField(blank=True, default='', max_length=80)),
                ('event_code', models.CharField(blank=True, default='', max_length=60)),
                ('event_label', models.CharField(blank=True, default='', max_length=100)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Succesvol'), ('partial', 'Deels gelukt'), ('failed', 'Mislukt')], default='failed', max_length=20)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data-importlog',
                'verbose_name_plural': 'Data-importlogs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='main_import_user_date_idx'), models.Index(fields=['data_type', 'created_at'], name='main_import_type_date_idx'), models.Index(fields=['team_code', 'created_at'], name='main_import_team_date_idx'), models.Index(fields=['status', 'created_at'], name='main_import_status_date_idx')],
            },
        ),
    ]
